# Generated by Django 4.1.3 on 2022-11-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clientegenerascript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientegenerascript',
            name='archivo',
            field=models.FileField(upload_to='Uploaded media/'),
        ),
    ]
